/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const CathedraIndexLazyImport = createFileRoute('/cathedra/')()
const CathedraHistoryLazyImport = createFileRoute('/cathedra/history')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CathedraIndexLazyRoute = CathedraIndexLazyImport.update({
  path: '/cathedra/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/cathedra/index.lazy').then((d) => d.Route),
)

const CathedraHistoryLazyRoute = CathedraHistoryLazyImport.update({
  path: '/cathedra/history',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/cathedra/history.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cathedra/history': {
      preLoaderRoute: typeof CathedraHistoryLazyImport
      parentRoute: typeof rootRoute
    }
    '/cathedra/': {
      preLoaderRoute: typeof CathedraIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CathedraHistoryLazyRoute,
  CathedraIndexLazyRoute,
])

/* prettier-ignore-end */
